name: keep_fit
description: Flutter project to view nearby gyms details.
publish_to: 'none'

version: 0.0.3+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  easy_localization: ^3.0.2
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  go_router: ^10.0.0
  fluttertoast: ^8.2.2
  analyzer: ^5.10.0
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  permission_handler: ^10.4.3
  cached_network_image: ^3.2.3
  flutter_logs: ^2.1.10
  flutter_local_notifications: ^15.1.0+1
  flutter_uploader: ^3.0.0-beta.4
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.1.0
  image_picker: ^1.0.1
  flutter_map: ^6.0.0-dev.2
  latlong2: ^0.9.0
  map_launcher: ^2.5.0+1
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.4
  freezed: ^2.4.1

dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true


  assets:
    - assets/translation/
    - assets/logo/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Century-Gothic
      fonts:
        - asset: assets/fonts/Century-Gothic-Bold.ttf
        - asset: assets/fonts/Century-Gothic-Regular.ttf