on:
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '19.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.6'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          name: keep-fit-v0.0.${{ github.run_number }}.apk
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}